// Code generated by github.com/gobuffalo/packr. DO NOT EDIT.

package preset

import "github.com/gobuffalo/packr"

// You can use the "packr clean" command to clean up this,
// and any other packr generated files.
func init() {
	packr.PackJSONBytes("./files", "blinkerpuffer.life", "\"I0xpZmUgMS4wNgotMSAtOQotMyAtOAoxIC04Ci00IC03Ci00IC02CjEgLTYKLTQgLTUKLTMgLTUKLTIgLTUKLTEgLTUKMCAtNQotMyAtMQotMiAtMQotNCAwCi0zIDAKLTEgMAowIDAKMSAwCi0zIDEKLTIgMQotMSAxCjAgMQotMiAyCi0xIDIKMSA0CjIgNAotMSA1CjQgNQotMiA2Ci0yIDcKNCA3Ci0yIDgKLTEgOAowIDgKMSA4CjIgOAozIDg=\"")
	packr.PackJSONBytes("./files", "galaxy.life", "\"I0xpZmUgMS4wNgotMjYgLTE4Ci0yMyAtMTgKLTIxIC0xOAotMjggLTE3Ci0yNyAtMTcKLTI1IC0xNwotMjMgLTE3Ci0yMiAtMTcKLTIxIC0xNwotMjcgLTE2Ci0yMCAtMTYKLTI4IC0xNQotMjcgLTE1Ci0yMSAtMTUKLTI3IC0xMwotMjEgLTEzCi0yMCAtMTMKLTI4IC0xMgotMjEgLTEyCi0yNyAtMTEKLTI2IC0xMQotMjUgLTExCi0yMyAtMTEKLTIxIC0xMQotMjAgLTExCi0yNyAtMTAKLTI1IC0xMAotMjIgLTEw\"")
	packr.PackJSONBytes("./files", "glider-gun.life", "\"I0xpZmUgMS4wNgo2IC00CjQgLTMKNiAtMwotNiAtMgotNSAtMgoyIC0yCjMgLTIKMTYgLTIKMTcgLTIKLTcgLTEKLTMgLTEKMiAtMQozIC0xCjE2IC0xCjE3IC0xCi0xOCAwCi0xNyAwCi04IDAKLTIgMAoyIDAKMyAwCi0xOCAxCi0xNyAxCi04IDEKLTQgMQotMiAxCi0xIDEKNCAxCjYgMQotOCAyCi0yIDIKNiAyCi03IDMKLTMgMwotNiA0Ci01IDQ=\"")
	packr.PackJSONBytes("./files", "glider.life", "\"I0xpZmUgMS4wNiAKMCAtMSAKMSAwIAotMSAxIAowIDEgCjEgMQ==\"")
	packr.PackJSONBytes("./files", "light-weight-space-ship.life", "\"I0xpZmUgMS4wNgotMSAtMgoyIC0yCi0yIC0xCi0yIDAKMiAwCi0yIDEKLTEgMQowIDEKMSAx\"")
	packr.PackJSONBytes("./files", "pentadecathlon.life", "\"I0xpZmUgMS4wNgotMyAtMQoyIC0xCi01IDAKLTQgMAotMiAwCi0xIDAKMCAwCjEgMAozIDAKNCAwCi0zIDEKMiAx\"")
	packr.PackJSONBytes("./files", "spider.life", "\"I0xpZmUgMS4wNgotNCAtMTEKNCAtMTEKLTEwIC0xMAotOSAtMTAKLTcgLTEwCi01IC0xMAotMyAtMTAKLTIgLTEwCjIgLTEwCjMgLTEwCjUgLTEwCjcgLTEwCjkgLTEwCjEwIC0xMAotMTMgLTkKLTEyIC05Ci0xMSAtOQotOSAtOQotNyAtOQotNiAtOQotNSAtOQo1IC05CjYgLTkKNyAtOQo5IC05CjExIC05CjEyIC05CjEzIC05Ci0xMyAtOAotOSAtOAotNyAtOAotMSAtOAoxIC04CjcgLTgKOSAtOAoxMyAtOAotOSAtNwotOCAtNwotMSAtNwoxIC03CjggLTcKOSAtNwotMTIgLTYKLTExIC02Ci0xIC02CjEgLTYKMTEgLTYKMTIgLTYKLTEyIC01Ci0xMSAtNQotOSAtNQotOCAtNQo4IC01CjkgLTUKMTEgLTUKMTIgLTUKLTggLTQKOCAtNA==\"")
}
