// Code generated by github.com/gobuffalo/packr. DO NOT EDIT.

package preset

import "github.com/gobuffalo/packr"

// You can use the "packr clean" command to clean up this,
// and any other packr generated files.
func init() {
	packr.PackJSONBytes("./files", "glider-gun.life", "\"I0xpZmUgMS4wNgo2IC00CjQgLTMKNiAtMwotNiAtMgotNSAtMgoyIC0yCjMgLTIKMTYgLTIKMTcgLTIKLTcgLTEKLTMgLTEKMiAtMQozIC0xCjE2IC0xCjE3IC0xCi0xOCAwCi0xNyAwCi04IDAKLTIgMAoyIDAKMyAwCi0xOCAxCi0xNyAxCi04IDEKLTQgMQotMiAxCi0xIDEKNCAxCjYgMQotOCAyCi0yIDIKNiAyCi03IDMKLTMgMwotNiA0Ci01IDQ=\"")
	packr.PackJSONBytes("./files", "glider.life", "\"I0xpZmUgMS4wNiAKMCAtMSAKMSAwIAotMSAxIAowIDEgCjEgMQ==\"")
}
